baseURL = 'https://ammacmahon.github.io/'
languageCode = 'en-us'
title = 'Anthony MacMahon'
theme = 'hugo-PaperMod-master'
publishDir = 'docs'

enableInlineShortcodes = true
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
enableEmoji = true
pygmentsUseClasses = true
mainsections = [ "posts", "papermod" ]

[minify]
disableXML = true

[[menu.main]]
name = "Writing"
url = "/writing/"
weight = 5

[[menu.main]]
name = "Posts"
url = "posts/"
weight = 10

[[menu.main]]
name = "Tags"
url = "tags/"
weight = 10


[outputs]
home = [ "HTML", "RSS", "JSON" ]

[params]
env = "production"
description = "Theme PaperMod - https://github.com/adityatelange/hugo-PaperMod"
defaultTheme = "auto"
ShowShareButtons = true
ShareButtons = ["linkedin", "twitter", "whatsapp", "bluesky","reddit","facebook","instagram"]
ShowReadingTime = true
disableAnchoredHeadings = true
displayFullLangName = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowRssButtonInSectionTermList = true
ShowAllPagesInArchive = true
ShowPageNums = true
ShowToc = true
images = [ "images/papermod-cover.png" ]

  [params.profileMode]
  enabled = false
  title = "PaperMod"
  imageUrl = "#"
  imageTitle = "my image"

    [[params.profileMode.buttons]]
    name = "Archives"
    url = "archives"

    [[params.profileMode.buttons]]
    name = "Tags"
    url = "tags"

  [params.homeInfoParams]
  Content = """
  ![Image by Colin Palangio](https://github.com/ammacmahon/ammacmahon.github.io/blob/main/assets/BlogProfilePic.jpg?raw=true)
-  Congratulations on finding my website. It exists.
-
- I'm a Toronto-based writer and policy professional.
-
- My plays have premiered at Tarragon Theatre, Soulpepper Theatre, Summerworks Festival, Live Five, and elsewhere. My play [The Jungle](https://www.playwrightscanada.com/Books/T/The-Jungle) was published by Playwrights Canada Press. You can find most of my plays on [New Play Exchange](https://newplayexchange.org/users/84656/anthony-macmahon) or contact me to ask for a copy and inquire about rights.
-
- I also write short stories, screenplays, and occasionally an article. I'll post those here.
-
- I sometimes write blog posts on things like theatre, municipal politics, and whatever else I'm thinking about. I don't want to start a newsletter or track any information. If you like what you read, that's cool.
"""

  [[params.socialIcons]]
  name = "bluesky"
  title = "Connect with me on Bluesky"
  url = "https://bsky.app/profile/amacmahon.bsky.social"

  [[params.socialIcons]]
  name = "Instagram"
  title = "Follow my instagram"
  url = "https://www.instagram.com/amacmahon"

  [params.assets]
  disableHLJS = true

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
noClasses = false

[services.instagram]
disableInlineCSS = true

[services.twitter]
disableInlineCSS = true
